version: '2'

services:
  finch:
    image: erikperkins/finch_app
    restart: on-failure
    hostname: finch
    mem_limit: 268435456
    environment:
      FINCH_ENV: production
    ports:
      - 1025:80
